CONTIKI = ../..
APPS = powertrace collect-view
PROJECT_SOURCEFILES += collect-common.c
CONTIKI_WITH_RIME = 1
DEFINES = PROJECT_CONF_H=\"project-conf.h\"

MODULES += core/net/mac/muchmac

include $(CONTIKI)/Makefile.include
